DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS medicalInfo;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE medicalInfo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  patientName TEXT NOT NULL,
  dob INTEGER NOT NULL,
  diagnosis TEXT NOT NULL,
  treatment TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);